# Generated by Django 4.2.2 on 2023-07-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="r_desc",
            field=models.TextField(null=True),
        ),
    ]
