# Generated by Django 4.2.2 on 2023-07-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_student_r_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="r_image",
            field=models.ImageField(upload_to="Recepie"),
        ),
    ]
